version: "3.8"
services:
  web:
    build: .
    command: python manage.py run -h 0.0.0.0
    ports:
      - "5001:5000"
    environment:
      - DB_URL=postgresql://postgres:postgres@db:5432/postgres
  db:
    image: postgres:12
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
volumes:
  pgdata: {}
